// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtyY_tVR9p9Q28w15F63pKOjD9jvsgFdc',
    appId: '1:741085251380:web:039b6f80a5d715a8d98761',
    messagingSenderId: '741085251380',
    projectId: 'fir-267bf',
    authDomain: 'fir-267bf.firebaseapp.com',
    storageBucket: 'fir-267bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1MSK4DitfXYn9Fs1IQ6Hi4rHzG8BAJ1o',
    appId: '1:741085251380:android:c5f438b2549c1feed98761',
    messagingSenderId: '741085251380',
    projectId: 'fir-267bf',
    storageBucket: 'fir-267bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5Gg4YperImru8hZdDlgt-R7OU0W-m_g',
    appId: '1:741085251380:ios:1406994197355101d98761',
    messagingSenderId: '741085251380',
    projectId: 'fir-267bf',
    storageBucket: 'fir-267bf.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5Gg4YperImru8hZdDlgt-R7OU0W-m_g',
    appId: '1:741085251380:ios:b51eb43fb5082924d98761',
    messagingSenderId: '741085251380',
    projectId: 'fir-267bf',
    storageBucket: 'fir-267bf.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
